## Metadata for IBM App Connect Enterprise configuration
## This metadata is used to augment the value.yaml to drive IPC UI for configuration of the Helm chart installation
## License configuration metadata     
license:
  __metadata:
    label: "License"
    type: "string"
    required: true
    options:
    - label: "Accepted"
      value: "accept"
    - label: "Not accepted"
value: "not accepted"

## Image configuration metadata
image:
  repository:
    __metadata:
      name: "repository"
      label: "repository"
      description: "Docker image location"
      type: "string"
      immutable: false
      required: true
  tag: 
    __metadata:
      name: "Docker image Tag"
      label: "Docker image Tag"
      description: "Docker image Tag"
      type: "string"
      immutable: false
      required: true
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to Always"
      type: "string"
      immutable: false
      required: true
      options:
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"
      - label: "IfNotPresent"
        value: "IfNotPresent"  
  pullSecret:
    __metadata:
      label: "Image pull secret"
      description: "Secret to use when pulling the image.  Set this when using an image from a private registry"
      type: "string"
      required: false
  
## Service configuration metadata
service:
  type: 
    __metadata:
      name: "Type"
      label: "Service Type"
      description: "This is the Service Type"
      type: "string"
      immutable: false
      required: true
      options:
        - label: "Cluster IP"
          value: "ClusterIP"
        - label: "Node Port"
          value: "NodePort"
        - label: "Load Balancer"
          value: "LoadBalancer"
  webuiPort: 
    __metadata:
      name: "webuiPort"
      label: "web ui port"
      description: "This is the web ui port number"
      type: "number"
      immutable: true
      required: true
  serverlistenerPort: 
    __metadata:
      name: "serverlistenerPort"
      label: "http port"
      description: "This is the http server listener port number"
      type: "number"
      immutable: true
      required: true

## Resource requests and limits configuration metadata
resources:
  __metadata:
    label: "Resources"
  requests:
    cpu: 
      __metadata: 
        label: "CPU request"
        description: "The requested CPU"
        type: "string"
        required: true   
    memory: 
      __metadata: 
        label: "Memory request"
        description: "The memory request"
        type: "string"
        required: true   
  limits:
    cpu: 
      __metadata: 
        label: "CPU limit"
        description: "The CPU limit"
        type: "string"
        required: true   
    memory: 
      __metadata: 
        label: "Memory limit"
        description: "The memory limit"
        type: "string"
        required: true   

replicaCount: 
  __metadata:
    name: "replicaCount"
    label: "Replica Count"
    description: "Deployment replicaCount - optional field dependent on workload"
    type: "number"
    immutable: false
    required: false

